name: Build sparse-bit-string
run-name: ${{ github.actor }} Running sparse-bit-string build.
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      BUILDKIT_PROGRESS: plain

    strategy:
      matrix:
        node-version: [18.20.2, 20.12.2]

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
    
    - run: npm ci
    - run: npm run build
    - run: npm run test
