name: Find all repos that depend on sparse-bit-string
run-name: ${{ github.actor }} Running sparse-bit-string ref check.
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v7
      id: projectRefs
      name: Search for references
      with:
        result-encoding: json
        debug: true
        script: |
          const searchQuery = `${context.repo.repo} in:file filename:package.json path:/`;
          const paginatedRepos = await github.paginate(github.rest.search.code, { q: searchQuery, per_page: 100 });
          const repos = paginatedRepos.map(item => item.repository.full_name);
          return repos;

    - name: Output results
      run: echo "${{ steps.projectRefs.outputs.result }}"
          

