name: Find all repos that depend on sparse-bit-string
run-name: ${{ github.actor }} Running sparse-bit-string ref check.
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v7
      id: projectRefs
      name: Search for references
      with:
        result-encoding: json
        debug: true
        script: |
          const searchQuery = `${context.repo.repo} in:file filename:package.json path:/`;
          const paginatedRepos = await github.paginate(github.rest.search.code, { q: searchQuery, per_page: 100 });
          const repos = paginatedRepos.map(item => item.repository.full_name);
          return repos.filter(repo => repo !== context.repo.full_name);

    - name: List of referencing repositories
      run: echo "${{ steps.projectRefs.outputs.result }}"
    
    - name: Get the SBOM for each repository
      uses: actions/github-script@v7
      id: getBoms
      with:
        result-encoding: json
        script: |
          const repos = steps.projectRefs.outputs.result;

          const boms = [];
          for (const repo of repos) {
            const bom = await github.rest.dependencyGraph.exportSbom({
              owner: repo.split('/')[0],
              repo: repo.split('/')[1],
            });
            console.log(`${repo}:\n${JSON.stringify(bom)}`);
            boms.push(bom);
          }
          return boms;


